### ISSUE TITLE
Theme doesn't support some recent content types

### ISSUE THREAD

**Issue by raspberrycoulis** [royalfig/smart#179]
When creating a post / page, and adding a new content type, there are some that aren't working or performing as expected with the latest version of the theme.

For example, the "Public preview" content type allows you to post publicly available content above the section, with all content below the section only available to paying members. If this content type is used, it sets the entire post / page to only be available to paying members only. 

Also, the "Callout" content type doesn't even appear on the post / page when added. Appreciate new features have been released by Ghost since the latest version of this theme was released, but it's one of the best themes I've come across in all my years using Ghost, so I'd love it to be updated to support the newer content types if possible!

**Comment by royalfig** [comment]
Thanks for the issue! 

Can you share some screenshots/examples? I'm not able to replicate the problems?

"Public preview" functions independently of a theme, so it shouldn't be impacted by the theme...

Callout should function as expected. 

![CleanShot 2022-12-13 at 14 34 48](https://user-images.githubusercontent.com/48868107/207428005-847e2014-71bb-4666-b19e-6c4c50c25dca.png)

**Comment by raspberrycoulis** [comment]
So, I'm using a modified theme at the moment which uses the two content types (Public Preview and Callout) on [this page](https://thenorthpoletimes.com/the-nice-list/) - this is how it looks with my current theme:

<img width="1244" alt="Screenshot 2022-12-15 at 09 09 48" src="https://user-images.githubusercontent.com/6330169/207819291-b49a0ece-5e74-47d7-8edd-566bd99e5ff9.png">

Further down the page, I've used the Public Preview content type, to hide away content available to premium members:

<img width="878" alt="Screenshot 2022-12-15 at 09 12 23" src="https://user-images.githubusercontent.com/6330169/207819557-67885db6-8457-4ef8-945a-f64d928989d1.png">

All good so far.

However, if I then activate your theme and view the page, it looks like this:

<img width="1110" alt="Screenshot 2022-12-15 at 09 10 05" src="https://user-images.githubusercontent.com/6330169/207819652-114f315a-4d0d-4c63-9d68-1b11a7d43292.png">

The entire page is then treated as for paying members only, which it is as with the Public Preview content type, I can choose to show some public content above where that feature is enabled on the page.

Hope this helps @royalfig!

**Comment by royalfig** [comment]
I'll be making a bigger announcement, but v2 of the theme is now released. It's a total redesign, so it may no longer be your cup of tea. Anyway, check out the demo: https://demo.ryanfeigenbaum.com
