### ISSUE TITLE
Ghost 5.32 complains about theme errors

### ISSUE THREAD

**Issue by MikeBishop** [royalfig/smart#232]
![image](https://user-images.githubusercontent.com/4273797/215878519-6fceb294-4f58-409a-9e2c-61257455b92a.png)

Also, I imagine "unkown" is a separate Ghost issue not related to this theme.  😉

**Comment by royalfig** [comment]
It looks like you're running an older version of the theme. Check out the newest version here: https://demo.ryanfeigenbaum.com

See the releases page for the latest download: https://github.com/royalfig/smart/releases

If you want to continue using your current version, you'll need to make the changes listed by `gscan`.
