### ISSUE TITLE
Site design: Color mode "light" does not work

### ISSUE THREAD

**Issue by DmytroLitvinov** [royalfig/smart#260]
Hi Ryan,

First of all thank you for your great theme. It is looking neat and cool 🙌 
Started to use it on my website https://dmytrolitvinov.com/

About the problem: I changed color mode to "light" and in preview it shows me as light, but when I refresh page even in preview it shows a dark after. On website it does not change at all.

Smart: v2.1.9
Browser: Chrome latest version
OS: macOS

**Comment by DmytroLitvinov** [comment]
On selecting "Light" in Settings.
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/16066485/222947162-087e2018-b690-4b3e-90d4-5bb8221cb31d.png">

But after the page refresh, 
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/16066485/222947195-e2e6f4e0-b397-43c1-ab35-932e12ea6d39.png">

**Comment by DmytroLitvinov** [comment]
Seems like there is Advanced logic for that. Found it at post https://ryanfeigenbaum.com/smart-2/

**Comment by royalfig** [comment]
Hi! Yeah, the logic is complex. The short of it is that it tries to do as much as possible to honor the preferences of the user and work automatically.

Here's what happens:

- The publication owners (you) sets the default (light/dark) in design settings, which specifies the default for the site.
- When someone visits the site, a script determines whether they've already set a preference on a previous visit or if they've set a system preference. If either of those conditions is true, then the site switches to the user's preference.
- If there's no preference set, then the site falls back to the option you set in Admin.

**Comment by DmytroLitvinov** [comment]
Thank you for an explanation, Ryan 👍
