### ISSUE TITLE
Feature request,bug and suggestion!

### ISSUE THREAD

**Issue by pauloiys** [royalfig/smart#273]
Hey @royalfig, 

just wanted to drop a quick note to express my appreciation for the work you've done on this repo. 

- I do love to see having the topics template included in this repo which makes it easy to showcase all tags on a single page. (eg- https://ryanfeigenbaum.com/topics/).
- And the author template is a nice touch too (like this one: https://ryanfeigenbaum.com/authors/).

I did notice one issue, though. On mobile devices, the homepage posts don't seem to be aligned properly (see screenshot: 

![image](https://user-images.githubusercontent.com/86748882/224489591-bb20f7b6-2c9c-4495-bf8b-83338d8cb670.png). 
If you could take a look at that, it would be much appreciated.

Thanks again for all your hard work on this project, and I'm really happy with the overall theme!

**Comment by royalfig** [comment]
Thanks so much! Just released a fix in version 2.2.0.
