### ISSUE TITLE
[BUG] TOC rendering issue when there are a lot of items

### ISSUE THREAD

**Issue by DmytroLitvinov** [royalfig/smart#275]
Recently, support of TOC was added in the theme.
And in the [demo page of smart theme](https://demo.ryanfeigenbaum.com/all-the-styles/#heading-4) we can see that not all items are in the viewport.

**Example of bug:**
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/16066485/224547545-0c2294a8-0309-477d-a0b3-143ea37c2258.png">
On that image we see in should also show 3 more items.
<img width="512" alt="image" src="https://user-images.githubusercontent.com/16066485/224547567-5d08d1fc-ed39-4460-b565-cffdeccc3a25.png">

**How it shown on Tablet devices:**
<img width="853" alt="image" src="https://user-images.githubusercontent.com/16066485/224547645-ea16b571-3f82-465e-9356-066e07fd7f07.png">

ACTUAL BEHAVIOUR: 
Not all item listed in TOC. The first items are cut.

EXPECTED BEHAVIOUR:
All item listed or not all but with scrolling functionality and it starts with showing first items and then from first to latest content it should.

**Comment by DmytroLitvinov** [comment]
Another overflow bug on https://ryanfeigenbaum.com/supercharge-your-ghost-theme-with-custom-settings/
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/16066485/224547897-022a10d9-381b-4bfb-b121-31d6eb3ee4df.png">

**Comment by royalfig** [comment]
Fixed in 2.2.2
