### ISSUE TITLE
FEATURE REQUEST: Author Page with Blog Authors and Post Count Label

### ISSUE THREAD

**Issue by pauloiys** [royalfig/smart#294]
![image](https://user-images.githubusercontent.com/86748882/230710882-0e8a42a1-1aba-406c-a45d-a6cd28faf6d0.png)

it would be beneficial to have a dedicated page that showcases all the blog authors along with the number of posts they have contributed according to the smart theme structure.

The enhanced author page would include a list of all the authors, with each author's name and a corresponding label indicating the number of posts they have written. This would provide valuable information to readers and highlight the contributions of each author to the blog.

Having the post count label would not only acknowledge the authors' contributions but also allow readers to easily identify prolific authors who have contributed significantly to the blog. It would also serve as an incentive for authors to continue writing and contributing to the blogging community.

hope you will implement this to the theme in an upcoming version update

idea by @kasuncfdo

**Comment by royalfig** [comment]
Cool idea. I'll think about implementing it in an upcoming version!

**Comment by royalfig** [comment]
The initial template was added in the latest release (2.6.2). To use it, create a new page and choose the **authors** template.
