### ISSUE TITLE
Issue: Dark/Light mode color Palette Issues in Theme Parts 

### ISSUE THREAD

**Issue by pauloiys** [royalfig/smart#299]
https://user-images.githubusercontent.com/86748882/233784070-40213279-328f-4b71-8f74-9d8ca9e7b17f.mp4

- There may be potential issues with the color palette in dark/light mode in certain areas of the theme, such as the comment section and the subscriber button when setting colors like `#6885a1` via the Ghost Admin.

![image](https://user-images.githubusercontent.com/86748882/233784248-8827b13e-2f7a-4c16-b045-476c7b6fe6c0.png)

![image](https://user-images.githubusercontent.com/86748882/233784891-002bcf92-4354-4e9c-bc9b-74b27361a343.png)
![image](https://user-images.githubusercontent.com/86748882/233784899-01d98afa-a15c-4ea0-bcc7-0a4e0474932d.png)

Just noticed the same issues on this to @royalfig

**Comment by royalfig** [comment]
Thanks for sharing. This happens because of how Ghost comments work, as they determine  the colors for comments on initial page load.

The easiest fix is for a user to refresh the page and the problem will go away. 

I'll think about other options like refreshing the pages or other strategies to counteract this behavior.

**Comment by pauloiys** [comment]
> Thanks for sharing. This happens because of how Ghost comments work, as they determine the colors for comments on initial page load.
> 
> The easiest fix is for a user to refresh the page and the problem will go away.
> 
> I'll think about other options like refreshing the pages or other strategies to counteract this behavior.

I See @royalfig , I need another help just when uploading the logo image from the ghost admin it still appears as text, is there any code that I can replace by modifying the theme if u can just provide one just now it would be a great help

**Comment by royalfig** [comment]
Fixed in latest release!
