### ISSUE TITLE
Show logo in Navbar

### ISSUE THREAD

**Issue by royalfig** [royalfig/smart#300]
>I See @royalfig , I need another help just when uploading the logo image from the ghost admin it still appears as text, is there any code that I can replace by modifying the theme if u can just provide one just now it would be a great help

Here's the files where the changes would need to happen. You'd need to to load the image, ensure its optimized, and fallback to text if not set. 

**Template**
https://github.com/royalfig/smart/blob/main/partials/navbar.hbs

**Style**
https://github.com/royalfig/smart/blob/main/assets/css/layout/navbar.css

_Originally posted by @pauloiys in https://github.com/royalfig/smart/issues/299#issuecomment-1518716219_

**Comment by pauloiys** [comment]
Thanks! Can you write the code here im not either familier with hbs

**Comment by projectnoa** [comment]
Would like to work on this one.

**Comment by royalfig** [comment]
That'd be awesome. Let me know if you have questions!
