### ISSUE TITLE
How to enable post excerptions on posts cards on homepage

### ISSUE THREAD

**Issue by pauloiys** [royalfig/smart#302]
![image](https://user-images.githubusercontent.com/86748882/234569849-450dac83-ddaf-4e59-a305-e6c9039d4a7e.png)
Hi, @royalfig just would like to know how to enable posts exception in three lines in post cards in the home page like this. need support with code according to the theme.

**Comment by royalfig** [comment]
You'll need to update this file: https://github.com/royalfig/smart/blob/bdb249bd9abe7f04f970b0e619d1a0997a238e2a/partials/card.hbs#enroll-beta

**Comment by pauloiys** [comment]
Just tried but not work well with 

`<p class='sm-excerpt'>{{excerpt}}</p>`
not only need to show a custom excerpt if there is no custom one, then the first post content in 30 sentences to show in excerpt.

can you point out the code with which lines of card.hbs to be exactly update with
