### ISSUE TITLE
[Feature Request] Custom page template with Contact form that support both dark & light mode

### ISSUE THREAD

**Issue by pauloiys** [royalfig/smart#310]
Hey @royalfig Currently, I would like to suggest the addition of a contact form feature to specific page/contect page that match with smart theme's native CSS. 

- The proposed solution involves creating a custom page template that will allow the site to add a form to any page using a single drop-down menu. it's even better rather than embedding a custom form on each individual page. It would be great to have this option available on the theme.
- also when embedding a custom form it's not compatible with the theme if I use ccs to inject with that. 

![image](https://github.com/royalfig/smart/assets/84648368/b5f8234d-44ad-45c5-949d-7b576a30fcb3)
![image](https://github.com/royalfig/smart/assets/86748882/1cb5d190-c4ab-48fe-9552-5a568110b2a6)

**Comment by royalfig** [comment]
Because there are so many different possible form providers, I think it's a better solution to handle this in the Editor rather than the template. It's easy to duplicate via snippets and can be styled like any other element.
