### ISSUE TITLE
Archive page not showing posts

### ISSUE THREAD

**Issue by iam-meghana** [royalfig/smart#314]
Hi!

On adding the archive page, and selecting the 'Archive' template, the page still shows up blank. 

I'm new to ghost, not sure if i'm missing something. Thanks for your help.

**Comment by royalfig** [comment]
Sorry for not responding sooner. 

The archive page works like this:

1. Create a page, Choose a name for it like "Archive" or "Today I learned." Select the custom template (as you did)
2. Internally tag posts with the page's slug. For Archive, this would be `#archive` and for Today I learned, it'd be `#today-i-learned"
3. Posts with these tags will now show up on the custom archive

This is the relevant line of code: https://github.com/royalfig/smart/blob/57d4ca8651e97fe1aa057be512a6b1c4edd50ae1/custom-archive.hbs#L12
