### ISSUE TITLE
Upload successful with errors

### ISSUE THREAD

**Issue by vincentzzzxxx** [royalfig/smart#387]
The theme "smart - 2.6.2" was installed successfully but we detected some errors. You are still able to activate and use the theme but it is recommended to fix these errors before you do so.
Errors
Highly recommended to fix, functionality could be restricted

[ Not all page features are being used](http://159.223.44.207/ghost/)
Some page features used by Ghost via the {{@page}} global are not implemented in this theme. Find more information about the {{@page}} global [here](https://ghost.org/docs/themes/helpers/page/).

Affected files:
page.hbs: @page.show_title_and_feature_image is not used
---------------------------------------------------------------------------
The theme "smart - 2.6.2" was installed successfully but we detected some errors. You are still able to activate and use the theme but it is recommended to fix these errors before you do so.
Errors
Highly recommended to fix, functionality could be restricted

[ Not all page features are being used](http://localhost:2368/ghost/)
Warnings
[ "card_assets" will now be included by default, including bookmark and gallery cards.](http://localhost:2368/ghost/)
[ Assets such as CSS & JS must use the {{asset}} helper](http://localhost:2368/ghost/)
---------------------------------------------------------------------------

Can you update to modify it and import the latest theme you are using for your website? it looks amazing, thank you!

**Comment by royalfig** [comment]
I may update this in the future, but there's too much hardcoded right now to make a release. However, you can, of course, fork and modify

**Comment by GitHubQueenn** [comment]
> I may update this in the future, but there's too much hardcoded right now to make a release. However, you can, of course, fork and modify

Was this ever figured out? Getting same error 10 months later :( I saw some files here updated 7 months ago, so I downloaded this repo as a .zip and imported as a theme, but it says the same error and even says it's v2.6.1 versus the 2.6.2 I somehow already have (even though it's from before those updates 7 months ago).
